qcheck-stm (#8)
* pagetable_spec starting

* im stuck

* implicit_transitive_deps false

this lets us exclude the multicoretests util library

* it compiles

* blahhhhhh. does it work now??????

* fuzz and check address non-neg

* make inconsistent assumptions over interface Util

Error: Files /home/rina/.opam/ocaml5/lib/qcheck-multicoretests-util/util.cmxa
       and lib/util/util.cmxa
       make inconsistent assumptions over interface Util
Had 1 error, waiting for filesystem changes...

* BIG: rename Util to Bincaml_util

* only nonzero nbytes

* stash

* fix shrinking

* dune fmt

* remove ppx expect nobase.common

* allow imptrandep

* add doc comments

* fix doc references to Bincaml_util

* remove dune root_module (not needed) and remove pull_request: